modLoader="javafml"

loaderVersion="[31,)"

[[mods]]

modId="dreamdimension"

version="1.0"

displayName="The Dream Dimension"

credits="IronicThoughts. Major thanks to MaeMyers (Can be found on Spotify as MAe Myers)!"

authors="IronicThoughts"

description='''
'''

[[dependencies.dreamdimension]] #optional
    modId="forge"
    mandatory=true
    versionRange="[31,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.dreamdimension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"